In [1]:
import pandas as pd
import re

In [9]:
population = pd.read_csv("C:/WORKSPACE/db/data-files/202409_202409_연령별인구현황_월간.csv")

In [3]:
population

,행정구역,2024년09월_계_총인구수,2024년09월_계_연령구간인구수,2024년09월_계_0세,2024년09월_계_1세,2024년09월_계_2세,2024년09월_계_3세,2024년09월_계_4세,2024년09월_계_5세,2024년09월_계_6세,...,2024년09월_여_91세,2024년09월_여_92세,2024년09월_여_93세,2024년09월_여_94세,2024년09월_여_95세,2024년09월_여_96세,2024년09월_여_97세,2024년09월_여_98세,2024년09월_여_99세,2024년09월_여_100세 이상
0,서울특별시 (1100000000),"9,350,995","9,350,995","38,100","38,486","40,625","42,608","44,377","47,757","51,072",...,"6,767","5,474","3,921","3,343","2,623","1,892","1,391",776,523.0,"1,184"
1,서울특별시 종로구 (1111000000),"138,879","138,879",415,419,467,471,516,512,580,...,131,105,87,63,52,46,34,21,8.0,33
2,서울특별시 종로구 청운효자동(1111051500),"11,143","11,143",52,35,43,48,46,50,50,...,13,10,11,3,6,4,1,2,0.0,4
3,서울특별시 종로구 사직동(1111053000),"8,995","8,995",21,31,38,33,35,38,54,...,8,3,10,7,5,3,2,1,1.0,3
4,서울특별시 종로구 삼청동(1111054000),"2,234","2,234",3,8,6,8,4,4,10,...,6,2,1,4,0,1,0,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1467,경기도 부천시 소사구 소사본동(4119453000),"25,385","25,385",157,135,140,154,130,135,134,...,29,19,10,11,12,2,4,4,3.0,6
1468,경기도 부천시 소사구 소사본1동(4119454000),"28,209","28,209",97,117,129,134,148,156,170,...,17,14,11,13,4,6,6,1,0.0,1
1469,경기도 부천시 소사구 범박동(4119455000),"28,317","28,317",216,285,280,288,300,297,340,...,9,13,4,4,6,1,6,1,3.0,5
1470,경기도 부천시 소사구 옥길동(4119456000),"31,381","31,381",164,193,227,275,301,337,358,...,15,11,8,7,6,5,3,2,3.0,0
1471,경기도 부천시 소사구 괴안동(4119457000),"18,500","18,500",63,54,70,74,86,87,83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
my_region = population[population['행정구역'].str.contains('시흥제1동')].index

In [5]:
population.iloc[my_region]

,행정구역,2024년09월_계_총인구수,2024년09월_계_연령구간인구수,2024년09월_계_0세,2024년09월_계_1세,2024년09월_계_2세,2024년09월_계_3세,2024년09월_계_4세,2024년09월_계_5세,2024년09월_계_6세,...,2024년09월_여_91세,2024년09월_여_92세,2024년09월_여_93세,2024년09월_여_94세,2024년09월_여_95세,2024년09월_여_96세,2024년09월_여_97세,2024년09월_여_98세,2024년09월_여_99세,2024년09월_여_100세 이상
300,서울특별시 금천구 시흥제1동(1154567000),"31,718","31,718",98,107,102,108,107,123,136,...,29,29,15,8,8,7,3,2,3.0,4

In [ ]:
population['2024년09월_계_총인구수'] = population['2024년09월_계_총인구수'].apply(lambda v: int(v.replace(",","")))

In [6]:
population = population.apply(lambda x: x.replace(",", "").astype(float) if x.dtype == "object" and x.name != '행정구역' else x)
population

,행정구역,2024년09월_계_총인구수,2024년09월_계_연령구간인구수,2024년09월_계_0세,2024년09월_계_1세,2024년09월_계_2세,2024년09월_계_3세,2024년09월_계_4세,2024년09월_계_5세,2024년09월_계_6세,...,2024년09월_여_91세,2024년09월_여_92세,2024년09월_여_93세,2024년09월_여_94세,2024년09월_여_95세,2024년09월_여_96세,2024년09월_여_97세,2024년09월_여_98세,2024년09월_여_99세,2024년09월_여_100세 이상
0,서울특별시 (1100000000),9350995.0,9350995.0,38100.0,38486.0,40625.0,42608.0,44377.0,47757.0,51072.0,...,6767.0,5474.0,3921.0,3343.0,2623.0,1892.0,1391.0,776.0,523.0,1184.0
1,서울특별시 종로구 (1111000000),138879.0,138879.0,415.0,419.0,467.0,471.0,516.0,512.0,580.0,...,131.0,105.0,87.0,63.0,52.0,46.0,34.0,21.0,8.0,33.0
2,서울특별시 종로구 청운효자동(1111051500),11143.0,11143.0,52.0,35.0,43.0,48.0,46.0,50.0,50.0,...,13.0,10.0,11.0,3.0,6.0,4.0,1.0,2.0,0.0,4.0
3,서울특별시 종로구 사직동(1111053000),8995.0,8995.0,21.0,31.0,38.0,33.0,35.0,38.0,54.0,...,8.0,3.0,10.0,7.0,5.0,3.0,2.0,1.0,1.0,3.0
4,서울특별시 종로구 삼청동(1111054000),2234.0,2234.0,3.0,8.0,6.0,8.0,4.0,4.0,10.0,...,6.0,2.0,1.0,4.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1467,경기도 부천시 소사구 소사본동(4119453000),25385.0,25385.0,157.0,135.0,140.0,154.0,130.0,135.0,134.0,...,29.0,19.0,10.0,11.0,12.0,2.0,4.0,4.0,3.0,6.0
1468,경기도 부천시 소사구 소사본1동(4119454000),28209.0,28209.0,97.0,117.0,129.0,134.0,148.0,156.0,170.0,...,17.0,14.0,11.0,13.0,4.0,6.0,6.0,1.0,0.0,1.0
1469,경기도 부천시 소사구 범박동(4119455000),28317.0,28317.0,216.0,285.0,280.0,288.0,300.0,297.0,340.0,...,9.0,13.0,4.0,4.0,6.0,1.0,6.0,1.0,3.0,5.0
1470,경기도 부천시 소사구 옥길동(4119456000),31381.0,31381.0,164.0,193.0,227.0,275.0,301.0,337.0,358.0,...,15.0,11.0,8.0,7.0,6.0,5.0,3.0,2.0,3.0,0.0
1471,경기도 부천시 소사구 괴안동(4119457000),18500.0,18500.0,63.0,54.0,70.0,74.0,86.0,87.0,83.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
population['2024년09월_계_총인구수'] = population['2024년09월_계_총인구수'].apply(lambda v: int(v.replace(",","")))

In [10]:
population_copy = population.copy()

In [11]:
population_copy.columns

Index(['행정구역', '2024년09월_계_총인구수', '2024년09월_계_연령구간인구수', '2024년09월_계_0세',
       '2024년09월_계_1세', '2024년09월_계_2세', '2024년09월_계_3세', '2024년09월_계_4세',
       '2024년09월_계_5세', '2024년09월_계_6세',
       ...
       '2024년09월_여_91세', '2024년09월_여_92세', '2024년09월_여_93세', '2024년09월_여_94세',
       '2024년09월_여_95세', '2024년09월_여_96세', '2024년09월_여_97세', '2024년09월_여_98세',
       '2024년09월_여_99세', '2024년09월_여_100세 이상'],
      dtype='object', length=310)

In [14]:
for col in population_copy.columns[1:]:
    population_copy[col] = population_copy[col].map(lambda v : float(str(v).replace(",", "") if v and str(v) != 'nan' else 0))

In [18]:
import numpy as np

nums = np.array(['123456'])
nums.astype(float)

array([123456.])